name: thorstream
favicon: null
layout_spectrum: 0.8011872365605086
typography_spectrum: 0.25479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
